spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmaniV/config-server
          username: AmaniV
          password: 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
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8070
#End of file