server:
  port: 8086
spring:
  main:
    #web-application-type: none
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    show-sql: true
  
logging:
  file.name: myapplication.log
  


---
spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  config:
    activate:
      on-profile: default

   
    